server:
  port: 8081


logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.boot.autoconfigure: INFO
    org.springframework.web.client.RestTemplate: DEBUG

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: demoapp
            client-secret: demoapp
            clientName: Keycloak
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/login/oauth2/code/demoapp
            scope:
            - openid
            - profile
            - email
        provider:
          keycloak:
            issuer-uri: https://keycloak-rhsso.apps.demo.sandbox1207.opentlc.com/realms/springboot
